#' Produce an APA-style narrative summary of SRTM analysis results
#'
#' @param results An object of class \code{srtm_analysis} as returned by
#'   \code{SRTMAnalyse()}.
#' @param alpha Numeric significance level for interpreting p-values
#'   (default \code{0.05}).
#'
#' @return A list with:
#'   \item{text}{A character vector of sentences suitable for a Results section.}
#'   \item{table}{A tibble summarising group sizes, mean baseline scores,
#'   standard deviations, and mean slopes for each baseline × trajectory group.}
#'
#' @export
report <- function(results, alpha = 0.05) {

  # --- safety checks --------------------------------------------------------
  if (!inherits(results, "srtm_analysis")) {
    rlang::abort(
      "`results` must be an object generated by SRTMAnalyse().",
      class = "srtm_reporting_bad_data"
    )
  }

  if (!is.numeric(alpha) || length(alpha) != 1L || !is.finite(alpha) ||
      alpha <= 0 || alpha >= 1) {
    rlang::abort(
      "`alpha` must be a single numeric value in the open interval (0, 1).",
      class = "srtm_reporting_bad_alpha"
    )
  }

  df       <- results$data
  settings <- results$settings
  group_first <- settings$group_first %||% "baseline"
  time_unit   <- settings$time_unit   %||% "time units"

  y1_name <- settings$y1 %||% "y1"

  # --- extract grouping info ------------------------------------------------
  baseGroups <- df$baseGroup
  trajGroups <- df$trajGroup
  total_n    <- nrow(df)

  n_base <- nlevels(base::droplevels(baseGroups))
  n_traj <- nlevels(base::droplevels(trajGroups))

  # trajectory label descriptors (customise as you like)
  traj_label_map <- c(
    "↑"  = "increasing trajectory",
    "↗" = "moderately increasing trajectory",
    "→" = "stable or flat trajectory",
    "↘" = "moderately decreasing trajectory",
    "↓"  = "decreasing trajectory"
  )

  traj_labels_used <- sort(unique(as.character(trajGroups)))
  traj_descriptions <- traj_label_map[traj_labels_used]
  traj_descriptions[is.na(traj_descriptions)] <- "trajectory group"

  trajectory_bullets <- paste0(
    "  * ", traj_labels_used, " = ", traj_descriptions,
    collapse = "\n"
  )

  # --- clustering method description ----------------------------------------
  clustering_method <- NULL
  if (!is.null(results$group_params$traj_overall) &&
      !is.null(results$group_params$traj_overall$preferred_method)) {
    clustering_method <- results$group_params$traj_overall$preferred_method
  } else if (!is.null(results$group_params$baseline_overall) &&
             !is.null(results$group_params$baseline_overall$preferred_method)) {
    clustering_method <- results$group_params$baseline_overall$preferred_method
  } else {
    clustering_method <- "density"
  }

  method_text <- if (identical(clustering_method, "kmeans")) {
    "k-means clustering"
  } else {
    "kernel density estimation (KDE) to identify local minima in the distribution"
  }

  # --- descriptive table for baseline × trajectory --------------------------
  summarised <- dplyr::summarise(
    dplyr::group_by(df, baseGroup, trajGroup),
    n     = dplyr::n(),
    Mean  = mean(.data[[y1_name]], na.rm = TRUE),
    SD    = stats::sd(.data[[y1_name]], na.rm = TRUE),
    Slope = mean(.data[["m01"]], na.rm = TRUE),
    .groups = "drop"
  )

  # --- top-level narrative --------------------------------------------------
  intro_sentence <- glue::glue(
    "A total of {total_n} participants had sufficient data for Self-Referenced Trajectory Modelling (SRTM)."
  )

  if (identical(group_first, "slope")) {
    grouping_sentence <- glue::glue(
      "Participants were first assigned to one of {n_traj} trajectory groups based on their historical-to-baseline slope (m01). ",
      "These trajectory groups were derived using {method_text}. ",
      "The trajectory groups used in this analysis were:\n{trajectory_bullets}\n\n",
      "Within each trajectory group, participants were further classified into {n_base} baseline-level groups using their baseline ({y1_name}) scores."
    )
  } else {
    grouping_sentence <- glue::glue(
      "Participants were first assigned to one of {n_base} baseline-level groups based on their baseline ({y1_name}) scores. ",
      "Within each baseline group, participants were then divided into {n_traj} trajectory groups based on their historical-to-baseline change (m01), using {method_text}. ",
      "The trajectory groups used in this analysis were:\n{trajectory_bullets}\n"
    )
  }

  table_sentence <- glue::glue(
    "Table 1 summarises the number of students in each baseline × trajectory combination, together with the mean baseline score ({y1_name}), standard deviation, and mean historical slope (Δy/Δt between y0 and y1) for each group."
  )

  # --- per-group APA-style sentences using Comparisons ----------------------
  comps <- results$Comparisons

  # join comparisons with baseline summary stats
  comps_joined <- dplyr::left_join(
    comps,
    summarised,
    by = c("baseGroup", "trajGroup")
  )

  # helper to format p without leading zero, using pretty_p where available
  format_p <- function(p, pretty_p) {
    if (is.na(p)) {
      return(NA_character_)
    }
    if (!is.na(pretty_p) && nzchar(pretty_p)) {
      # use pretty_p but drop leading zero if present
      return(sub("^0", "", pretty_p))
    }
    # fallback: raw p
    if (p < 1e-4) {
      return("<.0001")
    }
    out <- formatC(p, digits = 3, format = "fg")
    sub("^0", "", out)
  }

  per_group_sentences <- purrr::pmap_chr(
    comps_joined,
    function(baseGroup, trajGroup, t_value, diff, p, pretty_p, df,
             n, Mean, SD, Slope, ...) {

      # Handle missing stats gracefully
      if (is.null(Mean) || is.null(SD) || is.null(Slope) || is.null(diff) ||
          is.na(Mean) || is.na(SD) || is.na(Slope) || is.na(diff)) {
        return(glue::glue(
          "Group {baseGroup}{trajGroup} did not have sufficient data for descriptive or inferential statistics."
        ))
      }

      group_name <- glue::glue("Group {baseGroup}{trajGroup}")

      # direction of effect
      direction <- if (diff < 0) "lower" else "higher"
      abs_diff  <- abs(diff)

      # formatted numbers
      M_fmt     <- sprintf("%.2f", Mean)
      SD_fmt    <- sprintf("%.3f", SD)
      slope_fmt <- sprintf("%.2f", Slope)
      diff_fmt  <- sprintf("%.2f", abs_diff)

      # t / df
      t_fmt  <- if (is.na(t_value)) NA_character_ else sprintf("%.2f", t_value)
      df_fmt <- if (is.na(df)) NA_character_ else sprintf("%.0f", df)

      p_fmt  <- format_p(p, pretty_p)

      # significance text
      if (is.na(p)) {
        sig_clause  <- "and no statistical test could be computed for this group."
        stat_clause <- ""
      } else {
        if (p < alpha) {
          sig_clause <- "and this difference was statistically significant"
        } else {
          sig_clause <- "and this difference was not statistically significant"
        }
        stat_clause <- glue::glue(
          ", t({df_fmt}) = {t_fmt}, p = {p_fmt}"
        )
      }

      glue::glue(
        "{group_name} (M[{y1_name}] = {M_fmt}, SD[{y1_name}] = {SD_fmt}, Δy/Δt = {slope_fmt} per {time_unit}) ",
        "had an outcome that was {diff_fmt} points {direction} than expected, {sig_clause}{stat_clause}."
      )
    }
  )

  # --- assemble full text vector -------------------------------------------
  text <- c(
    intro_sentence,
    grouping_sentence,
    table_sentence,
    per_group_sentences
  )

  list(
    text  = text,
    table = summarised
  )
}
