#' Produce an APA-style summary of SRTM analysis results
#'
#' @description
#' Given an object returned by [SRTMAnalyse()], `report()` constructs:
#' \itemize{
#'   \item a set of APA-style sentences suitable for a Results section,
#'   \item a compact table of baseline × trajectory descriptors, and
#'   \item a collection of ggplot/patchwork figures that visualise
#'         cut-points, trajectories, and distributional summaries,
#'         including optional per-group panels.
#' }
#'
#' @param results An object of class \code{"srtm_analysis"} as returned by
#'   [SRTMAnalyse()].
#' @param alpha Numeric significance level for interpreting p-values
#'   (default \code{0.05}).
#' @param plot_palette Character palette name passed to plotting helpers
#'   (e.g., [setPlotPalette()], [plotSRTMPanel()],
#'   [plotSRTMPanelSummary()], [srtm_build_combined_cutpoint_plot()]).
#'   One of \code{"simple"}, \code{"pastel"}, \code{"colourblind"}, or
#'   \code{"greys"}. If \code{results$settings$plot_palette} is present,
#'   that value is used in preference.
#' @param debug Logical; if \code{TRUE}, emits verbose diagnostic messages
#'   (via [rlang::inform()]) and does not suppress errors when building
#'   figures. Intended mainly for development and debugging.
#'
#' @return A list with components:
#' \describe{
#'   \item{text}{Character vector of sentences suitable for a Results
#'     section.}
#'   \item{table}{A tibble summarising group sizes, mean baseline scores,
#'     standard deviations, and mean slopes for each baseline × trajectory
#'     type.}
#'   \item{figures}{A named list of ggplot/patchwork objects:
#'     \code{fig1_cutpoints}, \code{fig2_trajectories},
#'     \code{fig3_summary}, and \code{per_group} (itself a named list of
#'     group-specific patchwork figures). Any element may be \code{NULL}
#'     if figure construction fails.}
#'   \item{figure_order}{A character vector giving the intended high-level
#'     order in which figures should be printed, e.g.
#'     \code{c("fig1_cutpoints", "fig2_trajectories",
#'             "fig3_summary", "per_group")}.}
#' }
#'
#' @importFrom purrr pmap_chr
#'
#' @export
report <- function(results,
                   alpha = 0.05,
                   plot_palette = c("simple", "pastel", "modern", "colourblind", "greys"),
                   debug = FALSE) {

  # --- safety checks --------------------------------------------------------
  if (!inherits(results, "srtm_analysis")) {
    rlang::abort(
      "`results` must be an object generated by SRTMAnalyse().",
      class = "srtm_reporting_bad_data"
    )
  }

  if (!is.numeric(alpha) || length(alpha) != 1L || !is.finite(alpha) ||
      alpha <= 0 || alpha >= 1) {
    rlang::abort(
      "`alpha` must be a single numeric value in the open interval (0, 1).",
      class = "srtm_reporting_bad_alpha"
    )
  }

  if (!is.logical(debug) || length(debug) != 1L || is.na(debug)) {
    rlang::abort(
      "`debug` must be a single TRUE/FALSE value.",
      class = "srtm_reporting_bad_debug"
    )
  }

  df       <- results$data
  settings <- results$settings

  group_first       <- settings$group_first       %||% "baseline"
  time_unit         <- settings$time_unit        %||% "time units"
  traj_label_scheme <- settings$traj_label_scheme %||% "arrows"

  y0_name <- settings$y0 %||% "y0"
  y1_name <- settings$y1 %||% "y1"
  y2_name <- settings$y2 %||% "y2"

  # use palette from settings if present; otherwise function argument
  plot_palette <- settings$plot_palette %||% plot_palette[1] %||% "simple"

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): starting; group_first = '{group_first}', traj_label_scheme = '{traj_label_scheme}', palette = '{plot_palette}'."
      ),
      class = "srtm_report_debug"
    )
  }

  # --- extract grouping info ------------------------------------------------
  gv <- srtm_resolve_group_vars(results, debug = debug)

  baseGroups     <- df[[gv$base_col]]
  traj_var       <- df[[gv$traj_col]]
  traj_var_name  <- gv$traj_col
  group_first    <- gv$group_first
  total_n        <- nrow(df)
  n_base         <- nlevels(base::droplevels(baseGroups))
  n_traj         <- nlevels(base::droplevels(traj_var))

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): total_n = {total_n}, n_base = {n_base}, n_traj = {n_traj}; ",
        "trajectory variable = '{traj_var_name}'."
      ),
      class = "srtm_report_debug"
    )
  }

  # --------------------------------------------------------------------------
  # Dynamic phrasing depending on whether scores can be negative
  # --------------------------------------------------------------------------
  y_all <- c(
    df[[y0_name]],
    df[[y1_name]],
    df[[y2_name]]
  )
  y_all <- y_all[is.finite(y_all)]

  any_negative <- length(y_all) > 0 && min(y_all, na.rm = TRUE) < 0

  baseline_higher_phrase <- if (any_negative) {
    "more positive (less negative)"
  } else {
    "higher"
  }

  baseline_lower_phrase <- if (any_negative) {
    "more negative (further below zero)"
  } else {
    "lower"
  }

  # --------------------------------------------------------------------------
  # Baseline descriptors (very_low .. very_high) based on y1 distribution
  # --------------------------------------------------------------------------
  baseline_z_mid     <- 0.5   # ±0.5 SD around mean = "average"
  baseline_z_extreme <- 1.5   # beyond ±1.5 SD = "very high"/"very low"

  overall_mean_y1 <- mean(df[[y1_name]], na.rm = TRUE)
  overall_sd_y1   <- stats::sd(df[[y1_name]], na.rm = TRUE)

  # Guard against degenerate cases
  if (!is.finite(overall_sd_y1) || overall_sd_y1 <= 0) {
    overall_sd_y1 <- NA_real_
  }

  if (is.finite(overall_sd_y1)) {
    cut_very_high <- overall_mean_y1 + baseline_z_extreme * overall_sd_y1
    cut_high      <- overall_mean_y1 + baseline_z_mid     * overall_sd_y1
    cut_med       <- overall_mean_y1 - baseline_z_mid     * overall_sd_y1
    cut_low       <- overall_mean_y1 - baseline_z_extreme * overall_sd_y1
  } else {
    # Fallback: treat everything as "average" if SD is unusable
    cut_very_high <- Inf
    cut_high      <- Inf
    cut_med       <- -Inf
    cut_low       <- -Inf
  }

  baseline_rank_desc <- c(
    very_high = "a very high baseline score compared to the population",
    high      = "a moderately high baseline score compared to the population",
    med       = "an average baseline score compared to the population",
    low       = "a moderately low baseline score compared to the population",
    very_low  = "a very low baseline score compared to the population"
  )

  classify_baseline <- function(m) {
    if (!is.finite(m)) return("med")
    if (m >= cut_very_high) return("very_high")
    if (m >= cut_high)      return("high")
    if (m >= cut_med)       return("med")
    if (m >= cut_low)       return("low")
    "very_low"
  }

  # --------------------------------------------------------------------------
  # Trajectory descriptors from srtm_trajectory_label_schemes()
  # --------------------------------------------------------------------------
  traj_label_scheme <- settings$traj_label_scheme %||% "arrows"

  schemes <- srtm_trajectory_label_schemes()

  lab_col <- dplyr::case_match(
    traj_label_scheme,
    "arrows" ~ "arrow_label",
    "signs"  ~ "sign_label",
    "text"   ~ "text_label",
    .default = "text_label"
  )

  traj_keys <- schemes[[lab_col]]
  traj_desc <- schemes$report_description

  traj_desc_map <- traj_desc
  names(traj_desc_map) <- traj_keys

  # --------------------------------------------------------------------------
  # Combined baseline × trajectory bullets
  # --------------------------------------------------------------------------
  if (!("baseGroup" %in% names(df))) {
    trajectory_bullets <- "  * Baseline and trajectory groupings were used, but detailed descriptors could not be constructed."
  } else {

    traj_col <- gv$traj_col  # e.g. "trajType" or "trajGroup"

    combo_desc <- df %>%
      dplyr::filter(
        !is.na(.data$baseGroup),
        !is.na(.data[[traj_col]]),
        as.character(.data[[traj_col]]) != "Unknown"
      ) %>%
      dplyr::mutate(
        traj_for_report = .data[[traj_col]]
      ) %>%
      dplyr::group_by(baseGroup, traj_for_report) %>%
      dplyr::summarise(
        mean_y1 = mean(.data[[y1_name]], na.rm = TRUE),
        .groups = "drop"
      ) %>%
      dplyr::mutate(
        baseline_rank = vapply(mean_y1, classify_baseline, character(1)),
        baseline_desc = baseline_rank_desc[baseline_rank],
        traj_label_chr = as.character(traj_for_report),
        traj_desc      = traj_desc_map[traj_label_chr],
        traj_desc      = dplyr::if_else(
          is.na(traj_desc),
          "a particular trajectory pattern",
          traj_desc
        ),
        bullet = glue::glue(
          "  * {baseGroup}{traj_for_report}: {baseline_desc} with {traj_desc}"
        )
      )

    trajectory_bullets <- combo_desc %>%
      dplyr::arrange(baseGroup, traj_for_report) %>%
      dplyr::pull(bullet) %>%
      paste(collapse = "\n")
  }

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): trajectory bullets constructed:\n{trajectory_bullets}"
      ),
      class = "srtm_report_debug"
    )
  }

  # --- clustering method description ----------------------------------------
  clustering_method <- NULL
  if (!is.null(results$group_params$traj_overall) &&
      !is.null(results$group_params$traj_overall$preferred_method)) {
    clustering_method <- results$group_params$traj_overall$preferred_method
    src <- "traj_overall"
  } else if (!is.null(results$group_params$baseline_overall) &&
             !is.null(results$group_params$baseline_overall$preferred_method)) {
    clustering_method <- results$group_params$baseline_overall$preferred_method
    src <- "baseline_overall"
  } else {
    clustering_method <- "density"
    src <- "default"
  }

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): clustering_method = '{clustering_method}' (source = {src})."
      ),
      class = "srtm_report_debug"
    )
  }

  method_text <- if (identical(clustering_method, "kmeans")) {
    "k-means clustering"
  } else {
    "kernel density estimation (KDE) to identify local minima in the distribution"
  }

  # --- descriptive table for baseline × trajectory type ---------------------
  if (identical(traj_var_name, "trajType")) {
    summarised <- df %>%
      dplyr::group_by(baseGroup, trajType) %>%
      dplyr::summarise(
        n     = dplyr::n(),
        Mean  = mean(.data[[y1_name]], na.rm = TRUE),
        SD    = stats::sd(.data[[y1_name]], na.rm = TRUE),
        Slope = mean(.data[["m01"]], na.rm = TRUE),
        .groups = "drop"
      )
    join_keys <- c("baseGroup", "trajType")
  } else {
    summarised <- df %>%
      dplyr::group_by(baseGroup, trajGroup) %>%
      dplyr::summarise(
        n     = dplyr::n(),
        Mean  = mean(.data[[y1_name]], na.rm = TRUE),
        SD    = stats::sd(.data[[y1_name]], na.rm = TRUE),
        Slope = mean(.data[["m01"]], na.rm = TRUE),
        .groups = "drop"
      )
    join_keys <- c("baseGroup", "trajGroup")
  }

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): summarised table has {nrow(summarised)} rows; join_keys = {paste(join_keys, collapse = ', ')}."
      ),
      class = "srtm_report_debug"
    )
  }

  # --- top-level narrative --------------------------------------------------
  intro_sentence <- glue::glue(
    "A total of {total_n} participants had sufficient data for Self-Referenced Trajectory Modelling (SRTM)."
  )

  if (identical(group_first, "slope")) {
    grouping_sentence <- glue::glue(
      "Participants were first assigned to one of {n_traj} trajectory types based on their historical-to-baseline slope (m01). ",
      "These trajectory types were derived using {method_text}. ",
      "Within each trajectory type, participants were further classified into {n_base} baseline-level groups using their baseline ({y1_name}) scores. ",
      "The baseline × trajectory type combinations used in this analysis were:\n{trajectory_bullets}\n"
    )
  } else {
    grouping_sentence <- glue::glue(
      "Participants were first assigned to one of {n_base} baseline-level groups based on their baseline ({y1_name}) scores. ",
      "Within each baseline group, participants were then divided into {n_traj} trajectory types based on their historical-to-baseline change (m01), using {method_text}. ",
      "The baseline × trajectory type combinations used in this analysis were:\n{trajectory_bullets}\n"
    )
  }

  # --------------------------------------------------------------------------
  # Figure 1: combined cut-point plot
  # --------------------------------------------------------------------------
  cutpoint_plot <- tryCatch(
    {
      srtm_build_combined_cutpoint_plot(
        results      = results,
        plot_palette = plot_palette,
        debug        = debug
      )
    },
    error = function(e) {
      msg <- conditionMessage(e)
      if (debug) {
        rlang::inform(
          glue::glue(
            "report(): failed to build combined cut-point figure.\n  Error: {msg}"
          ),
          class = "srtm_report_debug"
        )
      } else {
        rlang::warn(
          glue::glue(
            "report(): failed to build combined cut-point figure; returning NULL. ",
            "Set debug = TRUE for more details. Error was: {msg}"
          ),
          class = "srtm_report_figure_fail"
        )
      }
      NULL
    }
  )

  figure1_sentence <- if (!is.null(cutpoint_plot)) {
    if (identical(group_first, "slope")) {
      glue::glue(
        "Figure 1 shows the empirical distribution of historical-to-baseline slopes (m01) and the cut-points used to define the overall trajectory types (top panel), ",
        "together with the corresponding baseline score distributions and cut-points within each trajectory type (lower panels)."
      )
    } else {
      glue::glue(
        "Figure 1 shows the empirical distribution of baseline scores ({y1_name}) and the cut-points used to define the overall baseline groups (top panel), ",
        "together with the corresponding historical slope distributions and cut-points within each baseline group (lower panels)."
      )
    }
  } else {
    NULL
  }

  table_sentence <- glue::glue(
    "Table 1 summarises the number of students in each baseline × trajectory type combination, together with the mean baseline score ({y1_name}), standard deviation, and mean historical slope (Δy/Δt between y0 and y1) for each group."
  )

  # --- outcome comparisons --------------------------------------------------
  comps <- results$Comparisons
  if (is.null(comps) || nrow(comps) == 0L) {
    rlang::warn(
      "No Comparisons component found in `results`; outcome-based sentences will be limited.",
      class = "srtm_reporting_no_comparisons"
    )
    comps <- NULL
  }

  if (!is.null(comps) &&
      "trajGroup" %in% names(comps) &&
      !("trajType" %in% names(comps)) &&
      "trajType" %in% names(summarised)) {
    comps <- dplyr::rename(comps, trajType = .data$trajGroup)
  }

  # --- slope comparisons (prepare for use) ----------------------------------
  slope_comps <- results$Slope_Comparisons %||% results$Comparisons_slopes
  if (!is.null(slope_comps) && nrow(slope_comps) > 0L) {
    if ("trajGroup" %in% names(slope_comps) &&
        !("trajType" %in% names(slope_comps)) &&
        "trajType" %in% names(summarised)) {
      slope_comps <- dplyr::rename(slope_comps, trajType = .data$trajGroup)
    }

    slope_comps <- slope_comps %>%
      dplyr::rename(
        t_slope        = .data$t_value,
        diff_slope     = .data$diff,
        p_slope        = .data$p,
        pretty_p_slope = .data$pretty_p,
        df_slope       = .data$df
      )
  } else {
    slope_comps <- NULL
  }

  # --- join comparisons with descriptives -----------------------------------
  if (!is.null(comps)) {
    comps_out <- comps %>%
      dplyr::rename(
        t_outcome        = .data$t_value,
        diff_outcome     = .data$diff,
        p_outcome        = .data$p,
        pretty_p_outcome = .data$pretty_p,
        df_outcome       = .data$df
      )

    full <- dplyr::left_join(
      summarised,
      comps_out,
      by = join_keys
    )

    if (!is.null(slope_comps)) {
      full <- dplyr::left_join(
        full,
        slope_comps,
        by = join_keys
      )
    } else {
      full <- full %>%
        dplyr::mutate(
          t_slope        = NA_real_,
          diff_slope     = NA_real_,
          p_slope        = NA_real_,
          pretty_p_slope = NA_character_,
          df_slope       = NA_real_
        )
    }
  } else {
    full <- summarised %>%
      dplyr::mutate(
        t_outcome        = NA_real_,
        diff_outcome     = NA_real_,
        p_outcome        = NA_real_,
        pretty_p_outcome = NA_character_,
        df_outcome       = NA_real_,
        t_slope          = NA_real_,
        diff_slope       = NA_real_,
        p_slope          = NA_real_,
        pretty_p_slope   = NA_character_,
        df_slope         = NA_real_
      )
  }

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): joined summary table has {nrow(full)} rows."
      ),
      class = "srtm_report_debug"
    )
  }

  # subset of columns for group-level iteration
  if ("trajType" %in% names(full)) {
    full_for_groups <- full %>%
      dplyr::select(
        baseGroup, trajType,
        n, Mean, SD, Slope,
        t_outcome, diff_outcome, p_outcome, pretty_p_outcome, df_outcome,
        t_slope, diff_slope, p_slope, pretty_p_slope, df_slope
      )
    traj_col_for_groups <- "trajType"
  } else {
    full_for_groups <- full %>%
      dplyr::select(
        baseGroup, trajGroup,
        n, Mean, SD, Slope,
        t_outcome, diff_outcome, p_outcome, pretty_p_outcome, df_outcome,
        t_slope, diff_slope, p_slope, pretty_p_slope, df_slope
      )
    traj_col_for_groups <- "trajGroup"
  }

  format_p <- function(p, pretty_p) {
    if (is.na(p)) {
      return(NA_character_)
    }
    if (!is.na(pretty_p) && nzchar(pretty_p)) {
      return(sub("^0", "", pretty_p))
    }
    if (p < 1e-4) {
      return("<.0001")
    }
    out <- formatC(p, digits = 3, format = "fg")
    sub("^0", "", out)
  }

  # --------------------------------------------------------------------------
  # Figure 2: trajectory panel plot (plotSRTMPanel)
  # --------------------------------------------------------------------------
  fig2 <- tryCatch(
    {
      plotSRTMPanel(
        data               = results$data,
        palette            = plot_palette,
        plot_time_discrete = FALSE
      )
    },
    error = function(e) {
      msg <- conditionMessage(e)
      if (debug) {
        rlang::inform(
          glue::glue(
            "report(): failed to build trajectory panel plot (Figure 2).\n  Error: {msg}"
          ),
          class = "srtm_report_debug"
        )
      } else {
        rlang::warn(
          glue::glue(
            "report(): failed to build trajectory panel plot (Figure 2); continuing without it. Error was: {msg}"
          ),
          class = "srtm_report_figure_fail"
        )
      }
      NULL
    }
  )

  figure2_sentence <- if (!is.null(fig2)) {
    glue::glue(
      "Figure 2 illustrates individual score trajectories across the three measurement points (Historical, Pre, Post) for each baseline × trajectory type combination. ",
      "Within each panel, the solid lines show how participants’ scores actually changed over time, whereas the dotted lines show how scores would be expected to change under the assumption of 'no net external influence'. ",
      "The greater the divergence between the solid and dotted lines around the Pre measurement (t = 0), the larger the departure from the pattern that would be expected in the absence of additional influences, though no causal interpretation is implied. ",
      "\n\n",
      "Moving from left to right across the columns, the trajectory panels are ordered from patterns that are relatively more positive (e.g., increasing or improving trajectories) to patterns that are relatively more negative (e.g., flat or declining trajectories) over the Historical-to-Pre interval. ",
      "This allows readers to compare how different trajectory types behave relative to the expected pattern within the same baseline group. ",
      "\n\n",
      "Moving from top to bottom down the rows, panels correspond to baseline groups with progressively {baseline_lower_phrase} initial scores. ",
      "Higher rows therefore represent groups with {baseline_higher_phrase} baseline levels, while lower rows represent groups with {baseline_lower_phrase} baseline levels across time. ",
      "Taken together, the grid makes it possible to see which combinations of baseline level and trajectory type show the strongest divergence from expected trajectories, without making any claims about the causes of those differences."
    )
  } else {
    NULL
  }

  # --------------------------------------------------------------------------
  # Figure 3: summary panel plot (plotSRTMPanelSummary)
  # --------------------------------------------------------------------------
  fig3 <- tryCatch(
    {
      plotSRTMPanelSummary(
        data        = results$data,
        palette     = plot_palette,
        geom        = "boxplot",
        show_legend = TRUE
      )
    },
    error = function(e) {
      msg <- conditionMessage(e)
      if (debug) {
        rlang::inform(
          glue::glue(
            "report(): failed to build summary panel plot (Figure 3).\n  Error: {msg}"
          ),
          class = "srtm_report_debug"
        )
      } else {
        rlang::warn(
          glue::glue(
            "report(): failed to build summary panel plot (Figure 3); continuing without it. Error was: {msg}"
          ),
          class = "srtm_report_figure_fail"
        )
      }
      NULL
    }
  )

  figure3_sentence <- if (!is.null(fig3)) {
    glue::glue(
      "Figure 3 summarises the distribution of scores at the Historical, Pre, and Post measurements for each baseline × trajectory type combination. ",
      "In each panel, the coloured bars (or filled violins) represent the observed distributions, whereas the hollow bars (white-filled with coloured outlines) represent the expected distributions under the assumption of 'no net external influence'. ",
      "\n\n",
      "In the boxplot version, the dark central line shows the median score for that group and time point, and the height of the box represents the interquartile range (the middle 50% of scores). ",
      "In the violin version, the width of each shape reflects the density of scores at different values. ",
      "Comparing the coloured and hollow elements at the Post time point therefore shows not only whether observed outcomes are higher or lower than expected, but also whether the spread of scores is tighter or more dispersed than would be expected under a 'no net external influence' assumption. ",
      "\n\n",
      "Horizontally, panels again move from more positive to more negative historical-to-baseline trajectory types, while vertically they move from baseline groups with {baseline_higher_phrase} initial scores at the top to groups with {baseline_lower_phrase} initial scores at the bottom. ",
      "Readers can thus see, for each baseline × trajectory type combination, both the direction and variability of departures from the expected distributions without inferring direct causality."
    )
  } else {
    NULL
  }

  # Optional bridge sentence if both fig2 and fig3 exist
  bridge_sentence <- if (!is.null(fig2) && !is.null(fig3)) {
    glue::glue(
      "Whereas Figure 2 focuses on individual trajectories relative to their expected paths, Figure 3 summarises the same information at the group level, highlighting differences in both central tendency and spread between observed and expected outcomes."
    )
  } else {
    NULL
  }

  # --------------------------------------------------------------------------
  # NEW: per-group detailed sections and group-specific figures
  # --------------------------------------------------------------------------
  group_text_blocks <- character(0)
  per_group_list    <- list()

  # convenient mapping from combo_desc for headings
  if (!is.null(combo_desc) && nrow(combo_desc) > 0L) {
    combo_map <- combo_desc %>%
      dplyr::mutate(
        code = paste0(baseGroup, traj_for_report)
      ) %>%
      dplyr::select(code, baseline_desc, traj_desc)
  } else {
    combo_map <- tibble::tibble(
      code          = character(0),
      baseline_desc = character(0),
      traj_desc     = character(0)
    )
  }

  # helper to get "Historical"/"Pre"/"Post" labels
  time_label_map <- c(
    y0 = "Historical",
    y1 = "Pre",
    y2 = "Post"
  )

  # starting figure index for per-group patchworks
  base_group_fig_index <- 4L

  if (nrow(full_for_groups) > 0L && "baseGroup" %in% names(df)) {

    for (i in seq_len(nrow(full_for_groups))) {
      row_i <- full_for_groups[i, , drop = FALSE]

      baseGroup_i <- as.character(row_i$baseGroup[[1]])
      traj_i <- as.character(row_i[[traj_col_for_groups]][[1]])

      code_i <- paste0(baseGroup_i, traj_i)

      # ---- outcome sentence reused from earlier logic ----------------------
      Mean_i      <- row_i$Mean[[1]]
      SD_i        <- row_i$SD[[1]]
      Slope_i     <- row_i$Slope[[1]]
      t_outcome_i <- row_i$t_outcome[[1]]
      diff_out_i  <- row_i$diff_outcome[[1]]
      p_out_i     <- row_i$p_outcome[[1]]
      pp_out_i    <- row_i$pretty_p_outcome[[1]]
      df_out_i    <- row_i$df_outcome[[1]]

      t_slope_i   <- row_i$t_slope[[1]]
      diff_slope_i<- row_i$diff_slope[[1]]
      p_slope_i   <- row_i$p_slope[[1]]
      pp_slope_i  <- row_i$pretty_p_slope[[1]]
      df_slope_i  <- row_i$df_slope[[1]]

      # basic checks
      if (is.null(Mean_i) || is.null(SD_i) || is.null(Slope_i) ||
          is.na(Mean_i) || is.na(SD_i) || is.na(Slope_i)) {
        outcome_sentence_i <- glue::glue(
          "Group {code_i} did not have sufficient data for descriptive or inferential statistics."
        )
        slope_sentence_i <- ""
      } else {

        direction_out <- if (!is.na(diff_out_i) && diff_out_i < 0) "lower" else "higher"
        abs_diff_out  <- if (is.na(diff_out_i)) NA_real_ else abs(diff_out_i)

        M_fmt_i     <- sprintf("%.2f", Mean_i)
        SD_fmt_i    <- sprintf("%.3f", SD_i)
        slope_fmt_i <- sprintf("%.2f", Slope_i)
        diff_fmt_i  <- if (is.na(abs_diff_out)) NA_character_ else sprintf("%.2f", abs_diff_out)

        t_out_fmt_i  <- if (is.na(t_outcome_i)) NA_character_ else sprintf("%.2f", t_outcome_i)
        df_out_fmt_i <- if (is.na(df_out_i)) NA_character_ else sprintf("%.0f", df_out_i)
        p_out_fmt_i  <- format_p(p_out_i, pp_out_i)

        if (is.na(p_out_i) || is.na(diff_out_i)) {
          out_sig_clause_i  <- "and no statistical test could be computed for this group."
          out_stat_clause_i <- ""
        } else {
          if (p_out_i < alpha) {
            out_sig_clause_i <- "and this difference was statistically significant"
          } else {
            out_sig_clause_i <- "and this difference was not statistically significant"
          }
          out_stat_clause_i <- glue::glue(
            ", t({df_out_fmt_i}) = {t_out_fmt_i}, p = {p_out_fmt_i}"
          )
        }

        outcome_sentence_i <- glue::glue(
          "Group {code_i} (M[{y1_name}] = {M_fmt_i}, SD[{y1_name}] = {SD_fmt_i}, Δy/Δt = {slope_fmt_i} per {time_unit}) ",
          "had an outcome that was {diff_fmt_i} points {direction_out} than expected, {out_sig_clause_i}{out_stat_clause_i}."
        )

        if (is.na(diff_slope_i) || is.na(p_slope_i)) {
          slope_sentence_i <- ""
        } else {
          slope_dir_i      <- if (diff_slope_i < 0) "decreased" else "increased"
          abs_diff_slope_i <- abs(diff_slope_i)
          diff_slope_fmt_i <- sprintf("%.2f", abs_diff_slope_i)
          t_slope_fmt_i    <- sprintf("%.2f", t_slope_i)
          df_slope_fmt_i   <- sprintf("%.0f", df_slope_i)
          p_slope_fmt_i    <- format_p(p_slope_i, pp_slope_i)
          slope_sig_i      <- if (p_slope_i < alpha) "statistically significant" else "not statistically significant"

          slope_sentence_i <- glue::glue(
            " The difference between the historical (y0–y1) and subsequent (y1–y2) slopes was {diff_slope_fmt_i} points per {time_unit} ({slope_dir_i}), ",
            "which was {slope_sig_i}, t({df_slope_fmt_i}) = {t_slope_fmt_i}, p = {p_slope_fmt_i}."
          )
        }
      }

      # ---- heading based on baseline + trajectory descriptors --------------
      if (nrow(combo_map) > 0L && code_i %in% combo_map$code) {
        baseline_desc_full <- combo_map$baseline_desc[combo_map$code == code_i][1]
        traj_desc_i        <- combo_map$traj_desc[combo_map$code == code_i][1]
      } else {
        baseline_desc_full <- "an average baseline score compared to the population"
        traj_desc_i        <- traj_desc_map[traj_i] %||% "a particular trajectory pattern"
      }

      # strip leading a/an and everything after "score"
      bd <- tolower(baseline_desc_full)
      bd <- sub("^(a|an)\\s+", "", bd)
      bd <- sub("\\s*score.*$", "", bd)
      if (!nzchar(bd)) bd <- "average baseline"
      bd <- paste0(toupper(substr(bd, 1, 1)), substr(bd, 2, nchar(bd)))

      heading_i <- glue::glue(
        "Group {code_i}: {bd} and {traj_desc_i}."
      )

      # ---- subset data for this group --------------------------------------
      if (traj_col_for_groups == "trajType") {
        df_g <- df %>%
          dplyr::filter(
            .data$baseGroup == !!baseGroup_i,
            .data$trajType  == !!traj_i
          )
      } else {
        df_g <- df %>%
          dplyr::filter(
            .data$baseGroup == !!baseGroup_i,
            .data$trajGroup == !!traj_i
          )
      }

      # ---- figure numbering -------------------------------------------------
      fig_idx_i <- base_group_fig_index + (i - 1L)

      # ---- panel (ii): median / IQR & Wilcoxon comparison at Post ----------
      obs_post <- df_g[[y2_name]]
      exp_post <- if ("exp_y2" %in% names(df_g)) df_g$exp_y2 else rep(NA_real_, nrow(df_g))

      obs_post <- obs_post[is.finite(obs_post)]
      exp_post <- exp_post[is.finite(exp_post)]

      # medians / IQRs
      med_obs <- if (length(obs_post)) stats::median(obs_post, na.rm = TRUE) else NA_real_
      med_exp <- if (length(exp_post)) stats::median(exp_post, na.rm = TRUE) else NA_real_

      iqr_obs <- if (length(obs_post)) {
        qs <- stats::quantile(obs_post, probs = c(.25, .75), na.rm = TRUE)
        qs[2] - qs[1]
      } else NA_real_

      iqr_exp <- if (length(exp_post)) {
        qs <- stats::quantile(exp_post, probs = c(.25, .75), na.rm = TRUE)
        qs[2] - qs[1]
      } else NA_real_

      # IQR comparison phrase
      iqr_phrase <- ""
      if (is.finite(iqr_obs) && is.finite(iqr_exp) && iqr_exp > 0) {
        ratio_iqr <- iqr_obs / iqr_exp
        if (ratio_iqr < 0.6) {
          iqr_phrase <- "The observed scores showed a much narrower spread than expected."
        } else if (ratio_iqr < 0.9) {
          iqr_phrase <- "The observed scores showed a somewhat narrower spread than expected."
        } else if (ratio_iqr <= 1.1) {
          iqr_phrase <- "The spread of observed scores was similar to the expected spread."
        } else if (ratio_iqr <= 1.5) {
          iqr_phrase <- "The observed scores showed a somewhat wider spread than expected."
        } else {
          iqr_phrase <- "The observed scores showed a much wider spread than expected."
        }
      }

      # Wilcoxon–Mann–Whitney test
      wilcox_sentence <- ""
      if (length(obs_post) >= 2L && length(exp_post) >= 2L) {
        wt <- tryCatch(
          stats::wilcox.test(obs_post, exp_post, alternative = "two.sided"),
          error = function(e) NULL
        )
        if (!is.null(wt)) {
          p_w  <- wt$p.value
          Wval <- unname(wt$statistic)
          p_w_fmt <- format_p(p_w, NA)
          sig_w <- if (p_w < alpha) "statistically significant" else "not statistically significant"
          wilcox_sentence <- glue::glue(
            " A Wilcoxon–Mann–Whitney test comparing observed and expected Post scores indicated that this difference in central tendency was {sig_w}, W = {round(Wval, 2)}, p = {p_w_fmt} (α = {alpha})."
          )
        } else {
          wilcox_sentence <- " A Wilcoxon–Mann–Whitney test could not be computed for this group."
        }
      } else if (length(obs_post) > 0 || length(exp_post) > 0) {
        wilcox_sentence <- " A Wilcoxon–Mann–Whitney test could not be computed because there were insufficient non-missing scores in one or both distributions."
      }

      med_sentence <- if (is.finite(med_obs) && is.finite(med_exp)) {
        glue::glue(
          "At the Post measurement, the median observed score was {round(med_obs, 2)}, compared to a median expected score of {round(med_exp, 2)}."
        )
      } else if (is.finite(med_obs)) {
        glue::glue(
          "At the Post measurement, the median observed score was {round(med_obs, 2)}, but the corresponding expected distribution was not available."
        )
      } else {
        ""
      }

      iqr_sentence <- if (nzchar(iqr_phrase)) iqr_phrase else ""

      panel_ii_sentence <- glue::glue(
        "Figure {fig_idx_i}ii shows the descriptive distributions of students’ observed scores compared to their expected distribution at each time point. ",
        "{med_sentence} {iqr_sentence}{wilcox_sentence}"
      )

      # ---- panel (iii): SD / skewness / kurtosis across time ---------------
      y0_vec <- df_g[[y0_name]]
      y1_vec <- df_g[[y1_name]]
      y2_vec <- df_g[[y2_name]]

      sd_vec <- c(
        y0 = stats::sd(y0_vec, na.rm = TRUE),
        y1 = stats::sd(y1_vec, na.rm = TRUE),
        y2 = stats::sd(y2_vec, na.rm = TRUE)
      )

      skew_vec <- c(
        y0 = if (length(na.omit(y0_vec)) > 2L) moments::skewness(y0_vec, na.rm = TRUE) else NA_real_,
        y1 = if (length(na.omit(y1_vec)) > 2L) moments::skewness(y1_vec, na.rm = TRUE) else NA_real_,
        y2 = if (length(na.omit(y2_vec)) > 2L) moments::skewness(y2_vec, na.rm = TRUE) else NA_real_
      )

      kurt_vec <- c(
        y0 = if (length(na.omit(y0_vec)) > 3L) moments::kurtosis(y0_vec, na.rm = TRUE) else NA_real_,
        y1 = if (length(na.omit(y1_vec)) > 3L) moments::kurtosis(y1_vec, na.rm = TRUE) else NA_real_,
        y2 = if (length(na.omit(y2_vec)) > 3L) moments::kurtosis(y2_vec, na.rm = TRUE) else NA_real_
      )

      panel_iii_sentence <- ""

      if (all(is.finite(sd_vec))) {
        t_sd_max <- names(sd_vec)[which.max(sd_vec)]
        t_sd_min <- names(sd_vec)[which.min(sd_vec)]

        sd_sentence <- glue::glue(
          "Figure {fig_idx_i}iii shows the underlying distributions of students’ scores at each time point. ",
          "For this group, variability in scores (standard deviation) was lowest at {time_label_map[[t_sd_min]]} and highest at {time_label_map[[t_sd_max]]}, ",
          "indicating that scores were most tightly clustered at {time_label_map[[t_sd_min]]} and most dispersed at {time_label_map[[t_sd_max]]}."
        )

        # skewness summary
        skew_finite <- skew_vec[is.finite(skew_vec)]
        skew_sentence <- ""
        if (length(skew_finite) > 0L) {
          avg_skew <- mean(skew_finite)
          if (abs(avg_skew) < 0.5) {
            skew_sentence <- " Across the three time points, the score distributions were approximately symmetric."
          } else if (avg_skew > 0) {
            skew_sentence <- " Across the three time points, the score distributions tended to show a longer tail towards higher scores."
          } else {
            skew_sentence <- " Across the three time points, the score distributions tended to show a longer tail towards lower scores."
          }
        }

        # kurtosis summary (relative within group)
        kurt_finite <- kurt_vec[is.finite(kurt_vec)]
        kurt_sentence <- ""
        if (length(kurt_finite) > 0L) {
          t_kurt_max <- names(kurt_vec)[which.max(kurt_vec)]
          t_kurt_min <- names(kurt_vec)[which.min(kurt_vec)]
          kurt_sentence <- glue::glue(
            " The distributions were most sharply peaked at {time_label_map[[t_kurt_max]]} and relatively flatter at {time_label_map[[t_kurt_min]]}."
          )
        }

        panel_iii_sentence <- paste0(sd_sentence, skew_sentence, kurt_sentence)
      }

      # ---- panel (i): reference to existing outcome sentence ----------------
      panel_i_sentence <- glue::glue(
        "Figure {fig_idx_i}i shows the trajectories of students’ observed scores compared to their expected trajectories for this group. ",
        "As can be seen, {outcome_sentence_i}{slope_sentence_i}"
      )

      # ---- overview sentence for the combined figure -----------------------
      figure_overview_sentence <- glue::glue(
        "Figure {fig_idx_i} shows the same data as Figures 2 and 3, but restricted to Group {code_i}. ",
        "Panel (i) focuses on individual trajectories, panel (ii) on the distribution of observed and expected scores at each time point, and panel (iii) on the underlying score distributions across time."
      )

      # ---- build patchwork figure: A|B|C with i, ii, iii tags --------------
      # A: trajectories (no facets, no legend)
      pA <- tryCatch(
        {
          plotSRTMPanel(
            data               = df_g,
            facet              = FALSE,
            palette            = plot_palette,
            plot_time_discrete = FALSE
          ) +
            ggplot2::theme(legend.position = "none")
        },
        error = function(e) NULL
      )

      # B: summary boxplots
      pB <- tryCatch(
        {
          plotSRTMPanelSummary(
            data        = df_g,
            facet       = FALSE,
            palette     = plot_palette,
            geom        = "boxplot",
            show_legend = FALSE
          )
        },
        error = function(e) NULL
      )

      # C: summary violins
      pC <- tryCatch(
        {
          plotSRTMPanelSummary(
            data        = df_g,
            facet       = FALSE,
            palette     = plot_palette,
            geom        = "violin",
            show_legend = FALSE
          )
        },
        error = function(e) NULL
      )

      group_fig <- NULL
      if (!is.null(pA) && !is.null(pB) && !is.null(pC)) {
        group_fig <- patchwork::wrap_plots(
          pA, pB, pC,
          ncol = 3
        ) +
          patchwork::plot_annotation(
            tag_levels = "i"  # i, ii, iii
          )
      }

      # ---- collect text for this group -------------------------------------
      group_text_i <- c(
        heading_i,
        figure_overview_sentence,
        panel_i_sentence,
        panel_ii_sentence,
        panel_iii_sentence
      )

      group_text_blocks <- c(group_text_blocks, group_text_i)

      per_group_list[[i]] <- list(
        group_code     = code_i,
        baseGroup      = baseGroup_i,
        traj_label     = traj_i,
        figure_number  = fig_idx_i,
        heading        = heading_i,
        text           = group_text_i[-1],  # everything after heading
        figure         = group_fig
      )
    } # end for each group
  }

  # give names to per_group list
  if (length(per_group_list) > 0L) {
    names(per_group_list) <- vapply(per_group_list, `[[`, character(1), "group_code")
  }

  # --------------------------------------------------------------------------
  # Assemble text in intended order
  # --------------------------------------------------------------------------
  text <- c(
    intro_sentence,
    grouping_sentence,
    figure1_sentence,
    table_sentence,
    figure2_sentence,
    bridge_sentence,
    figure3_sentence,
    group_text_blocks
  )

  if (debug) {
    rlang::inform(
      glue::glue(
        "report(): finished; returning {length(text)} sentences and figures (cutpoints = {if (is.null(cutpoint_plot)) 'NULL' else 'ok'}, ",
        "trajectories = {if (is.null(fig2)) 'NULL' else 'ok'}, ",
        "summary = {if (is.null(fig3)) 'NULL' else 'ok'}, ",
        "per-group figures = {length(per_group_list)})."
      ),
      class = "srtm_report_debug"
    )
  }

  list(
    text   = text,
    table  = summarised,
    figures = list(
      fig1_cutpoints    = cutpoint_plot,
      fig2_trajectories = fig2,
      fig3_summary      = fig3,
      per_group         = per_group_list
    ),
    figure_order = c(
      "fig1_cutpoints",
      "fig2_trajectories",
      "fig3_summary",
      "per_group"
    )
  )
}

